server:
  port: 8080
  servlet:
    context-path: /serviceb
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://db:1433;databaseName=lerna;
    username: dbadmin
    password: P@ssword
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
management:
  endpoint:
    health:
      enabled: true
      show-details: always
custom:
  configuration:
    source: microservice-b.yml on Config Server
    crossorigin: 
      urls: http://localhost:3000,http://dev.lerna.ca
      methods: HEAD,GET,POST,PUT,DELETE,PATCH
