server:
  port: 8081
spring:
  application:
    name: MicroserviceA
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=lerna;
    username: dbadmin
    password: P@ssword
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
management:
  endpoint:
    health:
      enabled: true
      show-details: always
